language: node_js
node_js:
  - "8.9.1"

sudo: true
dist: trusty

branches:
  only:
    - travisci    #Master only builds for prod. For now changing it to Travis CI Branch
                  #dev branch push will triger build for non prod deployment

# before_script:
#   # - npm install -g firebase-tools
#   - npm install

install:
  - npm i -g npm@5.7.1 # this should be deleted once 5.7.X is out of "pre-release"
  - npm ci             # instead of default npm install 
  - npm i node-sass
  - npm install -g @angular/cli@latest

script:
  - ng build --prod

# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    - soumyajit.dutta@nowfloats.com
    - khaja.nizamuddin@nowfloats.com
  slack:
    on_success: always
    on_failure: always